travel/config/routes.rb
Travel::Application.routes.draw do
  resources :cost_centers

  resources :trip_estimates

  namespace :charts do
	resources :samples
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

travel/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

travel/app/models/cost_center.rb
class CostCenter < ActiveRecord::Base
  attr_accessible :title
	
  has_many :trip_estimates

end

travel/app/models/trip_estimate.rb
require 'pp'
class TripEstimate < ActiveRecord::Base
  attr_accessible :air_cost, :booked_at, :cost_center, :departure_airport, :departure_city, :destination_airport, :destination_city, :ended_at, :estimated_car_daily_expense_with_tax, :estimated_hotel_nightly_expense_with_tax, :estimated_total_cost_usd, :hotel, :hotel_nights, :manager, :purpose, :rental_car_days, :started_at, :traveller, :cost_center_id

	after_validation :update_estimated_cost
	
	belongs_to :cost_center
	
	scope :q1, where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,1,1), Date.new(Time.now.year,4,1))
	scope :q2, where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,4,1), Date.new(Time.now.year,7,1))
	scope :q3, where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,7,1), Date.new(Time.now.year,10,1))
	scope :q4, where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,10,1), Date.new(Time.now.year+1,1,1))
	scope :year_to_date, where( 'ended_at >= ?', Date.new(Time.now.year,1,1))
	
	scope :recent, lambda { |items| TripEstimate.order('created_at DESC').limit(items) }
		
	# def self.q1total
	# 	year_to_date.where( 'ended_at < ?', Date.new(Time.now.year,4,1)).sum(:estimated_total_cost_usd)
	# end
	# 
	# def self.q2total
	# 	year_to_date.where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,4,1), Date.new(Time.now.year,7,1)).sum(:estimated_total_cost_usd)
	# end
	# 
	# def self.q3total
	# 	year_to_date.where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,7,1), Date.new(Time.now.year,10,1)).sum(:estimated_total_cost_usd)
	# end
	# 
	# def self.q4total
	# 	year_to_date.where( 'ended_at >= ? and ended_at < ?', Date.new(Time.now.year,10,1), Date.new(Time.now.year+1,1,1)).sum(:estimated_total_cost_usd)
	# end
	

	def self.q1total
		self.q1.sum(:estimated_total_cost_usd)
	end

	def self.q2total
		self.q2.sum(:estimated_total_cost_usd)
	end

	def self.q3total
		self.q3.sum(:estimated_total_cost_usd)
	end

	def self.q4total
		self.q4.sum(:estimated_total_cost_usd)
	end

	def self.ytd_total
		self.year_to_date.sum(:estimated_total_cost_usd)
	end
	
	def self.travellers
		year_to_date.select(:travellers).uniq
	end
		
	def self.in_sum_by(skopes, group_by_field, field_to_sum)
		the_hash = Hash.new { |h,k| h[k] = Array.new }
		skopes.each_with_index do |s,i| 
			hsh = self.send(s).group(group_by_field).sum(field_to_sum)
			hsh.each { |k,v| the_hash[k][i] = v.try(:to_f) || 0.0 }
		end
		final_result = the_hash.collect do |person,arr| 
			{ 
				:name => person, 
				:data => arr,
				:url => "/admin/trip_estimates?q%5Btraveller_contains%5D=#{person.downcase.gsub(/\s+/,'+')}"
         	}
		end
		pp ["the returned hash",final_result]
		final_result
	end
	
	def self.quarterly_report(*skopes)
		self.in_sum_by(skopes, :traveller, :estimated_total_cost_usd)
	end
		
private

	def update_estimated_cost
		self.estimated_total_cost_usd = total_hotel_expense + total_car_expense + total_air_expense rescue 0.0
	end
	
	def total_hotel_expense
		self.hotel_nights * self.estimated_hotel_nightly_expense_with_tax rescue 0.0
	end
	
	def total_car_expense
		self.rental_car_days * self.estimated_car_daily_expense_with_tax rescue 0.0
	end
	
	def total_air_expense
		self.air_cost rescue 0.0
	end
		
end

travel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

travel/app/controllers/charts/samples_controller.rb
class Charts::SamplesController < ApplicationController
  # GET /charts/samples
  # GET /charts/samples.json
  def index
	@h = LazyHighCharts::HighChart.new('graph') do |f| 
		f.options[:chart][:defaultSeriesType] = "area" 
		f.series(:name=>'John', :data=>[3, 20, 3, 5, 4, 10, 12 ,3, 5,6,7,7,80,9,9]) 
		f.series(:name=>'Jane', :data=> [1, 3, 4, 3, 3, 5, 4,-46,7,8,8,9,9,0,0,9] ) 
		end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @charts_samples }
    end
  end

  # def index
  #   @charts_samples = Charts::Sample.all
  # 
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @charts_samples }
  #   end
  # end

  # GET /charts/samples/1
  # GET /charts/samples/1.json
  def show
    @charts_sample = Charts::Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @charts_sample }
    end
  end

  # GET /charts/samples/new
  # GET /charts/samples/new.json
  def new
    @charts_sample = Charts::Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charts_sample }
    end
  end

  # GET /charts/samples/1/edit
  def edit
    @charts_sample = Charts::Sample.find(params[:id])
  end

  # POST /charts/samples
  # POST /charts/samples.json
  def create
    @charts_sample = Charts::Sample.new(params[:charts_sample])

    respond_to do |format|
      if @charts_sample.save
        format.html { redirect_to @charts_sample, notice: 'Sample was successfully created.' }
        format.json { render json: @charts_sample, status: :created, location: @charts_sample }
      else
        format.html { render action: "new" }
        format.json { render json: @charts_sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charts/samples/1
  # PUT /charts/samples/1.json
  def update
    @charts_sample = Charts::Sample.find(params[:id])

    respond_to do |format|
      if @charts_sample.update_attributes(params[:charts_sample])
        format.html { redirect_to @charts_sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charts_sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/samples/1
  # DELETE /charts/samples/1.json
  def destroy
    @charts_sample = Charts::Sample.find(params[:id])
    @charts_sample.destroy

    respond_to do |format|
      format.html { redirect_to charts_samples_url }
      format.json { head :no_content }
    end
  end
end

travel/app/controllers/cost_centers_controller.rb
class CostCentersController < InheritedResources::Base
end

travel/app/controllers/trip_estimates_controller.rb
class TripEstimatesController < InheritedResources::Base
end

travel/app/helpers/application_helper.rb
module ApplicationHelper
	
end

travel/app/helpers/charts/samples_helper.rb
module Charts::SamplesHelper
end

travel/app/helpers/cost_centers_helper.rb
module CostCentersHelper
end

travel/app/helpers/trip_estimates_helper.rb
module TripEstimatesHelper
end

travel/app/views/charts/samples/_form.html.erb
<%= form_for(@charts_sample) do |f| %>
  <% if @charts_sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charts_sample.errors.count, "error") %> prohibited this charts_sample from being saved:</h2>

      <ul>
      <% @charts_sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

travel/app/views/charts/samples/edit.html.erb
<h1>Editing charts_sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @charts_sample %> |
<%= link_to 'Back', charts_samples_path %>

travel/app/views/charts/samples/index.html.erb
<%= high_chart("my_id", @h) %>

travel/app/views/charts/samples/new.html.erb
<h1>New charts_sample</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_samples_path %>

travel/app/views/charts/samples/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_charts_sample_path(@charts_sample) %> |
<%= link_to 'Back', charts_samples_path %>

travel/app/views/cost_centers/_form.html.erb
<%= form_for(@cost_center) do |f| %>
  <% if @cost_center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost_center.errors.count, "error") %> prohibited this cost_center from being saved:</h2>

      <ul>
      <% @cost_center.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

travel/app/views/cost_centers/edit.html.erb
<h1>Editing cost_center</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost_center %> |
<%= link_to 'Back', cost_centers_path %>

travel/app/views/cost_centers/index.html.erb
<h1>Listing cost_centers</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cost_centers.each do |cost_center| %>
  <tr>
    <td><%= cost_center.title %></td>
    <td><%= link_to 'Show', cost_center %></td>
    <td><%= link_to 'Edit', edit_cost_center_path(cost_center) %></td>
    <td><%= link_to 'Destroy', cost_center, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cost center', new_cost_center_path %>

travel/app/views/cost_centers/new.html.erb
<h1>New cost_center</h1>

<%= render 'form' %>

<%= link_to 'Back', cost_centers_path %>

travel/app/views/cost_centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @cost_center.title %>
</p>


<%= link_to 'Edit', edit_cost_center_path(@cost_center) %> |
<%= link_to 'Back', cost_centers_path %>

travel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'highcharts' %>
  <%= javascript_include_tag 'highcharts/js/modules/exporting' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

travel/app/views/trip_estimates/_form.html.erb
<%= form_for(@trip_estimate) do |f| %>
  <% if @trip_estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_estimate.errors.count, "error") %> prohibited this trip_estimate from being saved:</h2>

      <ul>
      <% @trip_estimate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost_center %><br />
    <%= f.text_field :cost_center %>
  </div>
  <div class="field">
    <%= f.label :traveller %><br />
    <%= f.text_field :traveller %>
  </div>
  <div class="field">
    <%= f.label :manager %><br />
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :destination_city %><br />
    <%= f.text_field :destination_city %>
  </div>
  <div class="field">
    <%= f.label :destination_airport %><br />
    <%= f.text_field :destination_airport %>
  </div>
  <div class="field">
    <%= f.label :departure_city %><br />
    <%= f.text_field :departure_city %>
  </div>
  <div class="field">
    <%= f.label :departure_airport %><br />
    <%= f.text_field :departure_airport %>
  </div>
  <div class="field">
    <%= f.label :booked_at %><br />
    <%= f.datetime_select :booked_at %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br />
    <%= f.datetime_select :started_at %>
  </div>
  <div class="field">
    <%= f.label :ended_at %><br />
    <%= f.datetime_select :ended_at %>
  </div>
  <div class="field">
    <%= f.label :hotel %><br />
    <%= f.text_field :hotel %>
  </div>
  <div class="field">
    <%= f.label :air_cost %><br />
    <%= f.text_field :air_cost %>
  </div>
  <div class="field">
    <%= f.label :estimated_hotel_nightly_expense_with_tax %><br />
    <%= f.text_field :estimated_hotel_nightly_expense_with_tax %>
  </div>
  <div class="field">
    <%= f.label :hotel_nights %><br />
    <%= f.number_field :hotel_nights %>
  </div>
  <div class="field">
    <%= f.label :estimated_car_daily_expense_with_tax %><br />
    <%= f.text_field :estimated_car_daily_expense_with_tax %>
  </div>
  <div class="field">
    <%= f.label :rental_car_days %><br />
    <%= f.number_field :rental_car_days %>
  </div>
  <div class="field">
    <%= f.label :estimated_total_cost_usd %><br />
    <%= f.text_field :estimated_total_cost_usd %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br />
    <%= f.text_field :purpose %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

travel/app/views/trip_estimates/edit.html.erb
<h1>Editing trip_estimate</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_estimate %> |
<%= link_to 'Back', trip_estimates_path %>

travel/app/views/trip_estimates/index.html.erb
<h1>Listing trip_estimates</h1>

<table>
  <tr>
    <th>Cost center</th>
    <th>Traveller</th>
    <th>Manager</th>
    <th>Destination city</th>
    <th>Destination airport</th>
    <th>Departure city</th>
    <th>Departure airport</th>
    <th>Booked at</th>
    <th>Started at</th>
    <th>Ended at</th>
    <th>Hotel</th>
    <th>Air cost</th>
    <th>Estimated hotel nightly expense with tax</th>
    <th>Hotel nights</th>
    <th>Estimated car daily expense with tax</th>
    <th>Rental car days</th>
    <th>Estimated total cost usd</th>
    <th>Purpose</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trip_estimates.each do |trip_estimate| %>
  <tr>
    <td><%= trip_estimate.cost_center %></td>
    <td><%= trip_estimate.traveller %></td>
    <td><%= trip_estimate.manager %></td>
    <td><%= trip_estimate.destination_city %></td>
    <td><%= trip_estimate.destination_airport %></td>
    <td><%= trip_estimate.departure_city %></td>
    <td><%= trip_estimate.departure_airport %></td>
    <td><%= trip_estimate.booked_at %></td>
    <td><%= trip_estimate.started_at %></td>
    <td><%= trip_estimate.ended_at %></td>
    <td><%= trip_estimate.hotel %></td>
    <td><%= trip_estimate.air_cost %></td>
    <td><%= trip_estimate.estimated_hotel_nightly_expense_with_tax %></td>
    <td><%= trip_estimate.hotel_nights %></td>
    <td><%= trip_estimate.estimated_car_daily_expense_with_tax %></td>
    <td><%= trip_estimate.rental_car_days %></td>
    <td><%= trip_estimate.estimated_total_cost_usd %></td>
    <td><%= trip_estimate.purpose %></td>
    <td><%= link_to 'Show', trip_estimate %></td>
    <td><%= link_to 'Edit', edit_trip_estimate_path(trip_estimate) %></td>
    <td><%= link_to 'Destroy', trip_estimate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip estimate', new_trip_estimate_path %>

travel/app/views/trip_estimates/new.html.erb
<h1>New trip_estimate</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_estimates_path %>

travel/app/views/trip_estimates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cost center:</b>
  <%= @trip_estimate.cost_center %>
</p>

<p>
  <b>Traveller:</b>
  <%= @trip_estimate.traveller %>
</p>

<p>
  <b>Manager:</b>
  <%= @trip_estimate.manager %>
</p>

<p>
  <b>Destination city:</b>
  <%= @trip_estimate.destination_city %>
</p>

<p>
  <b>Destination airport:</b>
  <%= @trip_estimate.destination_airport %>
</p>

<p>
  <b>Departure city:</b>
  <%= @trip_estimate.departure_city %>
</p>

<p>
  <b>Departure airport:</b>
  <%= @trip_estimate.departure_airport %>
</p>

<p>
  <b>Booked at:</b>
  <%= @trip_estimate.booked_at %>
</p>

<p>
  <b>Started at:</b>
  <%= @trip_estimate.started_at %>
</p>

<p>
  <b>Ended at:</b>
  <%= @trip_estimate.ended_at %>
</p>

<p>
  <b>Hotel:</b>
  <%= @trip_estimate.hotel %>
</p>

<p>
  <b>Air cost:</b>
  <%= @trip_estimate.air_cost %>
</p>

<p>
  <b>Estimated hotel nightly expense with tax:</b>
  <%= @trip_estimate.estimated_hotel_nightly_expense_with_tax %>
</p>

<p>
  <b>Hotel nights:</b>
  <%= @trip_estimate.hotel_nights %>
</p>

<p>
  <b>Estimated car daily expense with tax:</b>
  <%= @trip_estimate.estimated_car_daily_expense_with_tax %>
</p>

<p>
  <b>Rental car days:</b>
  <%= @trip_estimate.rental_car_days %>
</p>

<p>
  <b>Estimated total cost usd:</b>
  <%= @trip_estimate.estimated_total_cost_usd %>
</p>

<p>
  <b>Purpose:</b>
  <%= @trip_estimate.purpose %>
</p>


<%= link_to 'Edit', edit_trip_estimate_path(@trip_estimate) %> |
<%= link_to 'Back', trip_estimates_path %>